package api

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"

	"xcloak-ngfw/database"
	"xcloak-ngfw/models"
	"xcloak-ngfw/services"
)

// RegisterAgentSecure — POST /api/agents/register
// Requires a valid, unused install token in the request body.
// Install tokens are generated by admins via POST /api/integrations/install-tokens.
func RegisterAgentSecure(c *gin.Context) {
	var reg struct {
		MachineID    string `json:"machine_id"`
		Hostname     string `json:"hostname"`
		OS           string `json:"os"`
		IPAddress    string `json:"ip_address"`
		InstallToken string `json:"install_token"` // required
	}

	if err := c.ShouldBindJSON(&reg); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	if reg.MachineID == "" || reg.Hostname == "" {
		c.JSON(400, gin.H{"error": "machine_id and hostname are required"})
		return
	}

	// ── Validate install token ────────────────────────────────
	if reg.InstallToken == "" {
		c.JSON(401, gin.H{
			"error": "install_token is required — generate one via Settings → Integrations → Install Tokens",
		})
		return
	}

	var tokenID int
	var used bool
	var expiresAt *time.Time

	err := database.DB.QueryRow(`
		SELECT id, used, expires_at
		FROM agent_install_tokens
		WHERE token = $1
	`, reg.InstallToken).Scan(&tokenID, &used, &expiresAt)

	if err != nil {
		c.JSON(401, gin.H{"error": "invalid install token"})
		return
	}

	if used {
		c.JSON(401, gin.H{"error": "install token has already been used"})
		return
	}

	if expiresAt != nil && time.Now().After(*expiresAt) {
		c.JSON(401, gin.H{"error": "install token has expired"})
		return
	}

	// ── Register the agent ────────────────────────────────────
	agent := models.Agent{
		MachineID: reg.MachineID,
		Hostname:  reg.Hostname,
		OS:        reg.OS,
		IPAddress: reg.IPAddress,
	}

	agentID, token, err := services.RegisterAgent(agent)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}

	// ── Mark token as used ────────────────────────────────────
	database.DB.Exec(`
		UPDATE agent_install_tokens
		SET used = TRUE, used_by_agent_id = $1, used_at = NOW()
		WHERE id = $2
	`, agentID, tokenID)

	services.LogEvent(
		"AGENT_REGISTERED",
		"Agent "+reg.Hostname+" ("+reg.MachineID+") registered",
		"system",
	)

	c.JSON(http.StatusOK, gin.H{
		"agent_id": agentID,
		"message":  "Agent Registered",
		"token":    token,
	})
}
