package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"

	"xcloak-ngfw/database"
	"xcloak-ngfw/models"
	"xcloak-ngfw/services"
)

// RegisterAgent — POST /api/agents/register
// Requires a valid, unused install token — generated by an admin via
// POST /api/integrations/install-tokens. The token determines which tenant
// the new agent belongs to.
// Returns agent_id + the hex token stored in the DB (generated once per machine_id).
func RegisterAgent(c *gin.Context) {

	var reg models.AgentRegistration

	if err := c.ShouldBindJSON(&reg); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	if reg.MachineID == "" || reg.Hostname == "" {
		c.JSON(400, gin.H{"error": "machine_id and hostname are required"})
		return
	}

	if reg.InstallToken == "" {
		c.JSON(401, gin.H{
			"error": "install_token is required — generate one via Settings → Integrations → Install Tokens",
		})
		return
	}

	// Atomically claim the token: only one concurrent request can flip
	// used=false -> true for a given token, so two requests racing on the
	// same token can't both register an agent off it.
	var tokenID, tenantID int

	err := database.DB.QueryRow(`
		UPDATE agent_install_tokens
		SET used = true, used_at = NOW()
		WHERE token = $1 AND used = false
		  AND (expires_at IS NULL OR expires_at > NOW())
		RETURNING id, tenant_id
	`, reg.InstallToken).Scan(&tokenID, &tenantID)

	if err != nil {
		c.JSON(401, gin.H{"error": "invalid, already-used, or expired install token"})
		return
	}

	agent := models.Agent{
		MachineID: reg.MachineID,
		Hostname:  reg.Hostname,
		OS:        reg.OS,
		IPAddress: reg.IPAddress,
	}

	// services.RegisterAgent returns (agentID int, token string, err error)
	// The token is a random hex string stored in agents.token column.
	agentID, token, err := services.RegisterAgent(agent, tenantID)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}

	if _, err := database.DB.Exec(`
		UPDATE agent_install_tokens SET used_by_agent_id = $1 WHERE id = $2
	`, agentID, tokenID); err != nil {
		// Token is already consumed above; this only loses the audit
		// link back to the agent it provisioned, not worth failing the
		// registration over.
		services.LogEvent("AGENT_REGISTER_WARN", "failed to record used_by_agent_id for install token "+fmt.Sprint(tokenID), "system")
	}

	services.LogEvent(
		"AGENT_REGISTERED",
		"Agent "+reg.Hostname+" ("+reg.MachineID+") registered",
		"system",
	)

	c.JSON(http.StatusOK, gin.H{
		"agent_id": agentID,
		"message":  "Agent Registered",
		"token":    token,
	})
}

func GetAgents(c *gin.Context) {

	agents, err := services.GetAgents(tenantIDFromContext(c))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, agents)
}

func GetAgentByID(c *gin.Context) {

	id := c.Param("id")

	agent, err := services.GetAgentByID(id, tenantIDFromContext(c))
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Agent not found"})
		return
	}

	c.JSON(http.StatusOK, agent)
}

func Heartbeat(c *gin.Context) {

	var req models.HeartbeatRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	if err := services.Heartbeat(req); err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}

	c.JSON(200, gin.H{"message": "Heartbeat Received"})
}
