package services

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/jung-kurt/gofpdf"

	"xcloak-ngfw/models"
)

// GenerateCompliancePDF renders a compliance report + its framework scores
// into a real PDF document, replacing the previous JSON-only export — the
// report data (summary stats, top risk agents, recent incidents, and each
// framework's pass/fail checks) was already real; this just gives it the
// PDF deliverable the feature has always claimed to produce.
func GenerateCompliancePDF(report *models.ComplianceReport, scores []FrameworkScore) ([]byte, error) {
	var summary models.ComplianceSummary
	_ = json.Unmarshal(report.Summary, &summary)

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(0, 10, "XCloak Security Suite", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 8, report.Title, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(0, 6, fmt.Sprintf("Generated by %s on %s", report.GeneratedBy, report.CreatedAt.Format("2006-01-02 15:04 UTC")), "", 1, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(4)

	sectionHeader(pdf, "Environment Summary")
	summaryRow(pdf, "Agents", fmt.Sprintf("%d total, %d online", summary.TotalAgents, summary.OnlineAgents))
	summaryRow(pdf, "Alerts", fmt.Sprintf("%d total, %d critical", summary.TotalAlerts, summary.CriticalAlerts))
	summaryRow(pdf, "Open Incidents", fmt.Sprintf("%d", summary.OpenIncidents))
	summaryRow(pdf, "Vulnerabilities", fmt.Sprintf("%d total, %d critical", summary.TotalVulns, summary.CriticalVulns))
	summaryRow(pdf, "Active IOCs", fmt.Sprintf("%d", summary.TotalIOCs))
	summaryRow(pdf, "Detection Rules", fmt.Sprintf("%d Sigma, %d YARA", summary.SigmaRules, summary.YaraRules))
	pdf.Ln(4)

	if len(summary.TopRiskAgents) > 0 {
		sectionHeader(pdf, "Top Risk Agents")
		for _, a := range summary.TopRiskAgents {
			summaryRow(pdf, a.Hostname, fmt.Sprintf("Risk %d (%s)", a.RiskScore, a.RiskLevel))
		}
		pdf.Ln(4)
	}

	if len(summary.RecentIncidents) > 0 {
		sectionHeader(pdf, "Recent Incidents")
		for _, i := range summary.RecentIncidents {
			summaryRow(pdf, fmt.Sprintf("#%d %s", i.ID, i.Title), fmt.Sprintf("%s / %s", i.Severity, i.Status))
		}
		pdf.Ln(4)
	}

	for _, fs := range scores {
		pdf.AddPage()
		pdf.SetFont("Helvetica", "B", 14)
		pdf.CellFormat(0, 9, fmt.Sprintf("%s — Score %d%%", fs.Framework, fs.Score), "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(100, 100, 100)
		pdf.CellFormat(0, 6, fmt.Sprintf("%d passed / %d failed", fs.Passed, fs.Failed), "", 1, "L", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(2)

		for _, check := range fs.Checks {
			status := "PASS"
			pdf.SetTextColor(0, 130, 0)
			if !check.Passed {
				status = "FAIL"
				pdf.SetTextColor(180, 0, 0)
			}
			pdf.SetFont("Helvetica", "B", 10)
			pdf.CellFormat(16, 6, status, "", 0, "L", false, 0, "")
			pdf.SetTextColor(0, 0, 0)
			pdf.SetFont("Helvetica", "", 10)
			pdf.CellFormat(0, 6, fmt.Sprintf("%s — %s", check.Name, check.Detail), "", 1, "L", false, 0, "")
		}
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func sectionHeader(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetFillColor(235, 235, 240)
	pdf.CellFormat(0, 8, title, "", 1, "L", true, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.Ln(1)
}

func summaryRow(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(55, 6, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}
