apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcloak.frontend.fullname" . }}
  labels:
    {{- include "xcloak.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xcloak.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xcloak.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "xcloak.frontend.fullname" . }}
          startupProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
