package repositories

import (
	"time"

	"xcloak-ngfw/database"
	"xcloak-ngfw/models"
)

// RegisterAgent upserts the agent by machine_id, scoped to tenantID (the
// tenant that owns the install token used to register).
//
// First registration: inserts a new row, returns the new id and the generated token.
// Re-registration (same machine_id): updates hostname, ip, os, last_seen and returns
// the EXISTING id and token — so the agent gets the same identity back after a restart.
// tenant_id is intentionally NOT updated on re-registration — an agent can't
// switch tenants just by re-registering with the same machine_id.
//
// Returns (agentID, token, error).
func RegisterAgent(agent models.Agent, tenantID int) (int, string, error) {

	var agentID int
	var token string

	err := database.DB.QueryRow(`
		INSERT INTO agents
		(machine_id, hostname, os, ip_address, status, token, last_seen, tenant_id)
		VALUES ($1, $2, $3, $4, 'online', $5, $6, $7)
		ON CONFLICT (machine_id)
		DO UPDATE SET
			hostname   = EXCLUDED.hostname,
			os         = EXCLUDED.os,
			ip_address = EXCLUDED.ip_address,
			status     = 'online',
			last_seen  = EXCLUDED.last_seen
		RETURNING id, token
	`,
		agent.MachineID,
		agent.Hostname,
		agent.OS,
		agent.IPAddress,
		agent.Token, // pre-generated by the service layer
		time.Now(),
		tenantID,
	).Scan(&agentID, &token)

	if err != nil {
		return 0, "", err
	}

	return agentID, token, nil
}

// GetAgentByToken looks up an agent by its bearer token.
// Used by RequireAgentAuth middleware on every agent-facing endpoint.
func GetAgentByToken(token string) (*models.Agent, error) {

	var agent models.Agent

	err := database.DB.QueryRow(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at, tenant_id
		FROM agents
		WHERE token = $1
	`, token).Scan(
		&agent.ID,
		&agent.MachineID,
		&agent.Hostname,
		&agent.OS,
		&agent.IPAddress,
		&agent.Status,
		&agent.LastSeen,
		&agent.CreatedAt,
		&agent.TenantID,
	)

	if err != nil {
		return nil, err
	}

	return &agent, nil
}

// GetAgents returns agents belonging to tenantID only. Use this from
// user-facing API paths that have a real tenant context from the request.
func GetAgents(tenantID int) ([]models.Agent, error) {
	return queryAgents(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at, tenant_id,
		       version, uptime_seconds, mem_alloc_mb, goroutines
		FROM agents
		WHERE tenant_id = $1
		ORDER BY id
	`, tenantID)
}

// GetAllAgents returns every agent across every tenant. For internal
// background jobs (health scoring, compliance, firewall sync, scheduler)
// that operate fleet-wide and have no per-request tenant context — not for
// user-facing API responses, which must use GetAgents(tenantID) instead.
func GetAllAgents() ([]models.Agent, error) {
	return queryAgents(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at, tenant_id,
		       version, uptime_seconds, mem_alloc_mb, goroutines
		FROM agents
		ORDER BY id
	`)
}

func queryAgents(query string, args ...interface{}) ([]models.Agent, error) {

	rows, err := database.DB.Query(query, args...)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var agents []models.Agent

	for rows.Next() {

		var agent models.Agent

		err := rows.Scan(
			&agent.ID,
			&agent.MachineID,
			&agent.Hostname,
			&agent.OS,
			&agent.IPAddress,
			&agent.Status,
			&agent.LastSeen,
			&agent.CreatedAt,
			&agent.TenantID,
			&agent.Version,
			&agent.UptimeSeconds,
			&agent.MemAllocMB,
			&agent.Goroutines,
		)

		if err != nil {
			continue
		}

		agents = append(agents, agent)
	}

	return agents, nil
}

// GetAgentByID returns the agent only if it belongs to tenantID — a request
// for another tenant's agent ID gets the same "not found" as a nonexistent
// one, so existence isn't leaked across tenants.
func GetAgentByID(id string, tenantID int) (*models.Agent, error) {

	var agent models.Agent

	err := database.DB.QueryRow(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at, tenant_id,
		       version, uptime_seconds, mem_alloc_mb, goroutines
		FROM agents
		WHERE id = $1 AND tenant_id = $2
	`, id, tenantID).Scan(
		&agent.ID,
		&agent.MachineID,
		&agent.Hostname,
		&agent.OS,
		&agent.IPAddress,
		&agent.Status,
		&agent.LastSeen,
		&agent.CreatedAt,
		&agent.TenantID,
		&agent.Version,
		&agent.UptimeSeconds,
		&agent.MemAllocMB,
		&agent.Goroutines,
	)

	if err != nil {
		return nil, err
	}

	return &agent, nil
}

func UpdateAgentHeartbeat(agentID int, version string, uptimeSeconds int64, memAllocMB, goroutines int) error {

	_, err := database.DB.Exec(`
		UPDATE agents
		SET last_seen = NOW(), status = 'online',
		    version = $2, uptime_seconds = $3, mem_alloc_mb = $4, goroutines = $5
		WHERE id = $1
	`, agentID, version, uptimeSeconds, memAllocMB, goroutines)

	return err
}
