package repositories

import (
	"time"

	"xcloak-ngfw/database"
	"xcloak-ngfw/models"
)

// RegisterAgent upserts the agent by machine_id.
//
// First registration: inserts a new row, returns the new id and the generated token.
// Re-registration (same machine_id): updates hostname, ip, os, last_seen and returns
// the EXISTING id and token — so the agent gets the same identity back after a restart.
//
// Returns (agentID, token, error).
func RegisterAgent(agent models.Agent) (int, string, error) {

	var agentID int
	var token string

	err := database.DB.QueryRow(`
		INSERT INTO agents
		(machine_id, hostname, os, ip_address, status, token, last_seen)
		VALUES ($1, $2, $3, $4, 'online', $5, $6)
		ON CONFLICT (machine_id)
		DO UPDATE SET
			hostname   = EXCLUDED.hostname,
			os         = EXCLUDED.os,
			ip_address = EXCLUDED.ip_address,
			status     = 'online',
			last_seen  = EXCLUDED.last_seen
		RETURNING id, token
	`,
		agent.MachineID,
		agent.Hostname,
		agent.OS,
		agent.IPAddress,
		agent.Token, // pre-generated by the service layer
		time.Now(),
	).Scan(&agentID, &token)

	if err != nil {
		return 0, "", err
	}

	return agentID, token, nil
}

// GetAgentByToken looks up an agent by its bearer token.
// Used by RequireAgentAuth middleware on every agent-facing endpoint.
func GetAgentByToken(token string) (*models.Agent, error) {

	var agent models.Agent

	err := database.DB.QueryRow(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at
		FROM agents
		WHERE token = $1
	`, token).Scan(
		&agent.ID,
		&agent.MachineID,
		&agent.Hostname,
		&agent.OS,
		&agent.IPAddress,
		&agent.Status,
		&agent.LastSeen,
		&agent.CreatedAt,
	)

	if err != nil {
		return nil, err
	}

	return &agent, nil
}

func GetAgents() ([]models.Agent, error) {

	rows, err := database.DB.Query(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at
		FROM agents
		ORDER BY id
	`)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var agents []models.Agent

	for rows.Next() {

		var agent models.Agent

		err := rows.Scan(
			&agent.ID,
			&agent.MachineID,
			&agent.Hostname,
			&agent.OS,
			&agent.IPAddress,
			&agent.Status,
			&agent.LastSeen,
			&agent.CreatedAt,
		)

		if err != nil {
			continue
		}

		agents = append(agents, agent)
	}

	return agents, nil
}

func GetAgentByID(id string) (*models.Agent, error) {

	var agent models.Agent

	err := database.DB.QueryRow(`
		SELECT id, machine_id, hostname, os, ip_address, status, last_seen, created_at
		FROM agents
		WHERE id = $1
	`, id).Scan(
		&agent.ID,
		&agent.MachineID,
		&agent.Hostname,
		&agent.OS,
		&agent.IPAddress,
		&agent.Status,
		&agent.LastSeen,
		&agent.CreatedAt,
	)

	if err != nil {
		return nil, err
	}

	return &agent, nil
}

func UpdateAgentHeartbeat(agentID int) error {

	_, err := database.DB.Exec(`
		UPDATE agents
		SET last_seen = NOW(), status = 'online'
		WHERE id = $1
	`, agentID)

	return err
}
