// Package docs provides OpenAPI 3.0 documentation for the XCloak API.
// Generated by swaggo/swag — run `make swagger` to regenerate after changing annotations.
//
// @title           XCloak Security Suite API
// @version         1.0
// @description     Next-generation firewall, EDR, SIEM, and MDM platform API.
//
// @contact.name    XCloak Security
// @contact.email   security@xcloak.io
//
// @license.name    Proprietary
//
// @host            localhost:8080
// @BasePath        /
//
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 JWT access token. Format: "Bearer <token>"
//
// @securityDefinitions.apikey  CookieAuth
// @in                          cookie
// @name                        token
// @description                 httpOnly session cookie set by POST /api/auth/login
package docs
