-- Remove seeded Sigma rule library for tenant 1.
DELETE FROM sigma_rules WHERE tenant_id = 1 AND title IN (
  'SSH Brute Force Login Attempts',
  'RDP Brute Force via Windows Event Log',
  'Web Shell Upload Detected',
  'Log4Shell Exploitation Attempt',
  'PowerShell Encoded Command Execution',
  'PowerShell Download Cradle',
  'Suspicious WMIC Remote Execution',
  'Linux Bash Reverse Shell',
  'Python Reverse Shell or Exec',
  'Scheduled Task Created via schtasks',
  'New Cron Job Added on Linux',
  'New Systemd Service Installed',
  'SSH Authorized Keys Modification',
  'New Local User Account Created',
  'Sudo Privilege Escalation to Root',
  'SUID / SGID Binary Execution',
  'Windows Token Impersonation',
  'Windows Security Log Cleared',
  'Linux Audit Log Tampered',
  'Suspicious Rundll32 Process Injection',
  'Security Tool Process Killed',
  'Shadow Password File Access',
  'Mimikatz Credential Dumping',
  'LSASS Memory Dump via ProcDump or TaskMgr',
  'Windows SAM Database Dump',
  'Network Port Scan Detected',
  'Active Directory Enumeration',
  'PsExec Remote Execution',
  'Pass-the-Hash Attack',
  'Kerberoasting Attack',
  'Sensitive Directory Archived for Exfiltration',
  'Base64 Encoded Payload in curl / wget',
  'DNS Tunneling Indicators',
  'Cobalt Strike Beacon Indicators',
  'Data Exfiltration via Cloud Storage',
  'Ransomware File Extension Pattern',
  'Shadow Copies Deleted',
  'Mass File Deletion',
  'Disk or MBR Wipe',
  'Kubernetes Privileged Container Launched',
  'Supply Chain: curl-bash Pipe Execution',
  'AWS CloudTrail: Root Account Login',
  'DCSync Attack Detected'
);
