//go:build !(linux && amd64)

// Stub for non-amd64 platforms. eBPF connect-event collection requires the
// x86 BPF bytecode generated by bpf2go and is only available on amd64 Linux.
// On all other targets this package compiles but returns ErrNotSupported.
package ebpf

import "errors"

// ErrNotSupported is returned on platforms where eBPF collection is unavailable.
var ErrNotSupported = errors.New("eBPF connect-event collector not supported on this architecture")

// ConnectEvent mirrors the type defined in loader.go for cross-platform consumers.
type ConnectEvent struct {
	TimestampNS   uint64
	PID           uint32
	UID           uint32
	Comm          string
	LocalAddress  string
	RemoteAddress string
}

// Collector is a no-op stub on non-amd64 targets.
type Collector struct{}

// NewCollector always returns ErrNotSupported on non-amd64 platforms.
func NewCollector() (*Collector, error) { return nil, ErrNotSupported }

// Read always returns ErrNotSupported.
func (c *Collector) Read() (ConnectEvent, error) { return ConnectEvent{}, ErrNotSupported }

// Close is a no-op.
func (c *Collector) Close() error { return nil }
