package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/jung-kurt/gofpdf"

	"xcloak-platform/models"
)

// Brand palette — kept as named RGB triples (gofpdf has no color-object
// type, just SetFillColor/SetDrawColor/SetTextColor(r,g,b int) calls) so
// every section draws from the same small set instead of ad-hoc literals.
var (
	colorNavy     = [3]int{17, 24, 57}    // header bands, headings
	colorAccent   = [3]int{37, 99, 235}   // links/accents, neutral bars
	colorSuccess  = [3]int{22, 163, 74}   // pass / good score
	colorWarning  = [3]int{217, 119, 6}   // mid score
	colorDanger   = [3]int{220, 38, 38}   // fail / bad score
	colorMuted    = [3]int{100, 100, 100} // secondary text
	colorBorder   = [3]int{222, 224, 230}
	colorRowFill  = [3]int{245, 246, 250} // zebra striping
	colorChipFill = [3]int{235, 238, 245}
)

const pageWidthA4 = 210.0 // mm, used to size full-bleed bands without hardcoding margins everywhere

// reportPDF wraps gofpdf.Fpdf with a Unicode-to-WinAnsi translator: the core
// Helvetica font only supports cp1252/WinAnsi, so any string containing an
// em dash, smart quote, etc. renders as mojibake unless passed through tr()
// first. Embedding *gofpdf.Fpdf means every existing pdf.XXX(...) call below
// keeps working unchanged via method promotion — only text arguments need
// wrapping in pdf.tr(...). A struct (not a package-level var) so concurrent
// PDF generation across requests can't race on a shared translator.
type reportPDF struct {
	*gofpdf.Fpdf
	tr func(string) string
}

func newReportPDF() *reportPDF {
	f := gofpdf.New("P", "mm", "A4", "")
	return &reportPDF{Fpdf: f, tr: f.UnicodeTranslatorFromDescriptor("")}
}

// severityColor maps a check/alert/vuln severity string to a brand color.
func severityColor(sev string) [3]int {
	switch sev {
	case "critical":
		return colorDanger
	case "high":
		return [3]int{234, 88, 12} // orange — distinct from "critical" red and "medium" amber
	case "medium":
		return colorWarning
	default: // "low" and anything unrecognized
		return colorAccent
	}
}

// scoreColor matches the frontend's existing 60/80% thresholds (see
// app/compliance/page.tsx's progress-bar coloring) so the PDF and the UI
// agree on what counts as good/borderline/bad.
func scoreColor(score int) [3]int {
	switch {
	case score >= 80:
		return colorSuccess
	case score >= 60:
		return colorWarning
	default:
		return colorDanger
	}
}

func scoreLabel(score int) string {
	switch {
	case score >= 80:
		return "Strong"
	case score >= 60:
		return "Needs Attention"
	default:
		return "Critical Gaps"
	}
}

func setFill(pdf *reportPDF, c [3]int) { pdf.SetFillColor(c[0], c[1], c[2]) }
func setDraw(pdf *reportPDF, c [3]int) { pdf.SetDrawColor(c[0], c[1], c[2]) }
func setText(pdf *reportPDF, c [3]int) { pdf.SetTextColor(c[0], c[1], c[2]) }

// GenerateCompliancePDF renders a compliance report + its framework scores
// into a branded, multi-section PDF: a cover page with an at-a-glance
// posture score, a narrative executive summary with severity-breakdown
// charts, a risk/incidents page, and one detailed scorecard page per
// framework — replacing the original flat text/table-only rendering.
func GenerateCompliancePDF(report *models.ComplianceReport, scores []FrameworkScore) ([]byte, error) {
	var summary models.ComplianceSummary
	_ = json.Unmarshal(report.Summary, &summary)

	pdf := newReportPDF()
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 20)
	pdf.AliasNbPages("")
	pdf.SetFooterFunc(func() { drawFooter(pdf, report) })

	drawCoverPage(pdf, report, summary, scores)
	drawExecutiveSummary(pdf, report, summary)
	drawRiskAndIncidents(pdf, summary)
	for _, fs := range scores {
		drawFrameworkPage(pdf, fs)
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// ── Cover page ───────────────────────────────────────────────────────────

func drawCoverPage(pdf *reportPDF, report *models.ComplianceReport, summary models.ComplianceSummary, scores []FrameworkScore) {
	pdf.AddPage()

	// Full-bleed navy header band with the product wordmark.
	setFill(pdf, colorNavy)
	pdf.Rect(0, 0, pageWidthA4, 48, "F")
	setText(pdf, [3]int{255, 255, 255})
	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetXY(15, 14)
	pdf.CellFormat(0, 10, pdf.tr("XCloak Security Suite"), "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetXY(15, 28)
	pdf.CellFormat(0, 8, pdf.tr("Compliance Assessment Report"), "", 1, "L", false, 0, "")

	pdf.SetXY(15, 58)
	setText(pdf, colorNavy)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(0, 9, pdf.tr(report.Title), "", 1, "L", false, 0, "")
	setText(pdf, colorMuted)
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, pdf.tr(fmt.Sprintf("Generated by %s on %s", report.GeneratedBy, report.CreatedAt.Format("2006-01-02 15:04 UTC"))), "", 1, "L", false, 0, "")
	pdf.Ln(8)

	if len(scores) > 0 {
		avg := 0
		for _, fs := range scores {
			avg += fs.Score
		}
		avg /= len(scores)

		// Overall-posture badge: a colored rounded box with the headline
		// number, sized as the focal point of the page.
		c := scoreColor(avg)
		x, y := pdf.GetX(), pdf.GetY()
		setFill(pdf, c)
		pdf.RoundedRect(x, y, 60, 32, 3, "1234", "F")
		setText(pdf, [3]int{255, 255, 255})
		pdf.SetFont("Helvetica", "B", 24)
		pdf.SetXY(x, y+5)
		pdf.CellFormat(60, 12, fmt.Sprintf("%d%%", avg), "", 1, "C", false, 0, "")
		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetXY(x, y+19)
		pdf.CellFormat(60, 6, pdf.tr(scoreLabel(avg)), "", 1, "C", false, 0, "")

		// Per-framework mini bars next to the badge, one row each.
		barX := x + 70
		barY := y
		pdf.SetXY(barX, barY)
		setText(pdf, colorNavy)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 6, "Framework Scores", "", 1, "L", false, 0, "")
		barY += 7
		maxBarW := pageWidthA4 - 15 - barX - 25
		for _, fs := range scores {
			drawMiniScoreBar(pdf, barX, barY, maxBarW, fs.Framework, fs.Score)
			barY += 7
		}
		pdf.SetXY(15, y+38)
	}

	pdf.Ln(6)
	sectionHeader(pdf, "Environment at a Glance")
	drawStatCardRow(pdf, []statCard{
		{"Agents", fmt.Sprintf("%d", summary.TotalAgents), fmt.Sprintf("%d online", summary.OnlineAgents)},
		{"Alerts", fmt.Sprintf("%d", summary.TotalAlerts), fmt.Sprintf("%d critical", summary.CriticalAlerts)},
		{"Incidents", fmt.Sprintf("%d", summary.OpenIncidents), "open"},
	})
	pdf.Ln(4)
	drawStatCardRow(pdf, []statCard{
		{"Vulnerabilities", fmt.Sprintf("%d", summary.TotalVulns), fmt.Sprintf("%d critical", summary.CriticalVulns)},
		{"Active IOCs", fmt.Sprintf("%d", summary.TotalIOCs), "tracked"},
		{"Detection Rules", fmt.Sprintf("%d", summary.SigmaRules+summary.YaraRules), fmt.Sprintf("%d Sigma, %d YARA", summary.SigmaRules, summary.YaraRules)},
	})
}

// drawMiniScoreBar renders one "Framework  [====    ] 62%" row.
func drawMiniScoreBar(pdf *reportPDF, x, y, barW float64, label string, score int) {
	pdf.SetXY(x, y)
	setText(pdf, [3]int{0, 0, 0})
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(38, 5, pdf.tr(label), "", 0, "L", false, 0, "")

	trackX := x + 38
	setFill(pdf, colorBorder)
	pdf.RoundedRect(trackX, y+0.5, barW, 4, 1.5, "1234", "F")
	if score > 0 {
		setFill(pdf, scoreColor(score))
		pdf.RoundedRect(trackX, y+0.5, barW*float64(score)/100.0, 4, 1.5, "1234", "F")
	}
	pdf.SetXY(trackX+barW+2, y)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(12, 5, fmt.Sprintf("%d%%", score), "", 0, "L", false, 0, "")
}

type statCard struct {
	Label, Value, Sub string
}

// drawStatCardRow lays out up to 3 equal-width rounded stat cards side by
// side — used in place of the old plain "label: value" text rows.
func drawStatCardRow(pdf *reportPDF, cards []statCard) {
	x0, y0 := pdf.GetX(), pdf.GetY()
	usable := pageWidthA4 - 30 // page width minus left+right margins
	gap := 4.0
	w := (usable - gap*float64(len(cards)-1)) / float64(len(cards))
	h := 22.0

	for i, c := range cards {
		x := x0 + float64(i)*(w+gap)
		setFill(pdf, colorRowFill)
		setDraw(pdf, colorBorder)
		pdf.RoundedRect(x, y0, w, h, 2, "1234", "FD")

		setText(pdf, colorMuted)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetXY(x+3, y0+3)
		pdf.CellFormat(w-6, 4, pdf.tr(c.Label), "", 1, "L", false, 0, "")

		setText(pdf, colorNavy)
		pdf.SetFont("Helvetica", "B", 14)
		pdf.SetXY(x+3, y0+8)
		pdf.CellFormat(w-6, 7, pdf.tr(c.Value), "", 1, "L", false, 0, "")

		setText(pdf, colorMuted)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetXY(x+3, y0+16)
		pdf.CellFormat(w-6, 4, pdf.tr(c.Sub), "", 1, "L", false, 0, "")
	}
	pdf.SetXY(x0, y0+h)
}

// ── Executive summary ────────────────────────────────────────────────────

func drawExecutiveSummary(pdf *reportPDF, report *models.ComplianceReport, summary models.ComplianceSummary) {
	pdf.AddPage()
	pageTitle(pdf, "Executive Summary")

	sectionHeader(pdf, "Overview")
	setText(pdf, [3]int{0, 0, 0})
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5.5, pdf.tr(executiveNarrative(report, summary)), "", "L", false)
	pdf.Ln(4)

	if len(summary.AlertsBySeverity) > 0 {
		sectionHeader(pdf, "Alerts by Severity")
		drawSeverityBars(pdf, summary.AlertsBySeverity, summary.TotalAlerts)
		pdf.Ln(4)
	}
	if len(summary.VulnsBySeverity) > 0 {
		sectionHeader(pdf, "Vulnerabilities by Severity")
		drawSeverityBars(pdf, summary.VulnsBySeverity, summary.TotalVulns)
		pdf.Ln(4)
	}
}

// executiveNarrative composes a short prose summary purely from numbers the
// report already computed — no new scoring, just turning the raw stats this
// feature already had into a readable lead paragraph instead of starting
// straight in on tables.
func executiveNarrative(report *models.ComplianceReport, s models.ComplianceSummary) string {
	posture := "stable"
	if s.CriticalAlerts > 0 || s.CriticalVulns > 0 || s.OpenIncidents > 0 {
		posture = "requiring attention"
	}
	offline := s.TotalAgents - s.OnlineAgents

	text := fmt.Sprintf(
		"This %s report covers %d monitored agent(s), of which %d are currently online",
		report.ReportType, s.TotalAgents, s.OnlineAgents,
	)
	if offline > 0 {
		text += fmt.Sprintf(" and %d offline", offline)
	}
	text += fmt.Sprintf(
		". Overall environment posture is %s: %d alert(s) have been recorded (%d critical), "+
			"%d incident(s) remain open, and %d vulnerabilit(y/ies) have been identified across the fleet "+
			"(%d critical). %d active threat indicator(s) and %d detection rule(s) (%d Sigma, %d YARA) "+
			"are currently in force.",
		posture, s.TotalAlerts, s.CriticalAlerts, s.OpenIncidents, s.TotalVulns,
		s.CriticalVulns, s.TotalIOCs, s.SigmaRules+s.YaraRules, s.SigmaRules, s.YaraRules,
	)
	return text
}

// drawSeverityBars renders one horizontal bar per severity level present in
// the map, longest-first, colored consistently with the rest of the report.
func drawSeverityBars(pdf *reportPDF, bySeverity map[string]int, total int) {
	if total == 0 {
		total = 1 // avoid div-by-zero; every bar will just render as 0-width
	}
	order := []string{"critical", "high", "medium", "low"}
	for _, sev := range order {
		count, ok := bySeverity[sev]
		if !ok {
			continue
		}
		drawOneSeverityBar(pdf, sev, count, total)
	}
	// Catch any severity label outside the known set (defensive — current
	// severity values are always one of the four above) so nothing silently
	// disappears from the chart.
	extra := []string{}
	for sev := range bySeverity {
		known := false
		for _, o := range order {
			if sev == o {
				known = true
				break
			}
		}
		if !known {
			extra = append(extra, sev)
		}
	}
	sort.Strings(extra)
	for _, sev := range extra {
		drawOneSeverityBar(pdf, sev, bySeverity[sev], total)
	}
}

func drawOneSeverityBar(pdf *reportPDF, sev string, count, total int) {
	x, y := pdf.GetX(), pdf.GetY()
	setText(pdf, [3]int{0, 0, 0})
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(x, y)
	pdf.CellFormat(22, 5.5, capitalize(sev), "", 0, "L", false, 0, "")

	barX := x + 22
	barMaxW := 130.0
	setFill(pdf, colorBorder)
	pdf.RoundedRect(barX, y+0.5, barMaxW, 4.5, 1, "1234", "F")
	if count > 0 {
		w := barMaxW * float64(count) / float64(total)
		setFill(pdf, severityColor(sev))
		pdf.RoundedRect(barX, y+0.5, w, 4.5, 1, "1234", "F")
	}
	pdf.SetXY(barX+barMaxW+3, y)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(10, 5.5, fmt.Sprintf("%d", count), "", 1, "L", false, 0, "")
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]-32) + s[1:] // ASCII upper for first byte; severities are always plain lowercase ascii
}

// ── Risk & incidents ─────────────────────────────────────────────────────

func drawRiskAndIncidents(pdf *reportPDF, summary models.ComplianceSummary) {
	if len(summary.TopRiskAgents) == 0 && len(summary.RecentIncidents) == 0 {
		return
	}
	pdf.AddPage()
	pageTitle(pdf, "Risk & Incidents")

	if len(summary.TopRiskAgents) > 0 {
		sectionHeader(pdf, "Top Risk Agents")
		tableHeaderRow(pdf, []colSpec{{"Hostname", 90}, {"Risk Score", 35}, {"Level", 0}})
		for i, a := range summary.TopRiskAgents {
			zebra := i%2 == 1
			startRow(pdf, zebra)
			cellText(pdf, a.Hostname, 90, false)
			cellText(pdf, fmt.Sprintf("%d", a.RiskScore), 35, false)
			setText(pdf, severityColor(riskLevelToSeverity(a.RiskLevel)))
			cellText(pdf, a.RiskLevel, 0, true)
			setText(pdf, [3]int{0, 0, 0})
		}
		pdf.Ln(4)
	}

	if len(summary.RecentIncidents) > 0 {
		sectionHeader(pdf, "Recent Incidents")
		tableHeaderRow(pdf, []colSpec{{"Incident", 110}, {"Severity", 35}, {"Status", 0}})
		for i, inc := range summary.RecentIncidents {
			zebra := i%2 == 1
			startRow(pdf, zebra)
			cellText(pdf, fmt.Sprintf("#%d %s", inc.ID, inc.Title), 110, false)
			setText(pdf, severityColor(inc.Severity))
			cellText(pdf, capitalize(inc.Severity), 35, false)
			setText(pdf, [3]int{0, 0, 0})
			cellText(pdf, inc.Status, 0, true)
		}
	}
}

// riskLevelToSeverity maps the risk-level label this codebase already uses
// (critical/high/medium/low, same vocabulary as alert/vuln severity) onto
// the shared severityColor palette so risk levels render in the same colors
// elsewhere in the report.
func riskLevelToSeverity(level string) string {
	switch level {
	case "Critical", "critical":
		return "critical"
	case "High", "high":
		return "high"
	case "Medium", "medium":
		return "medium"
	default:
		return "low"
	}
}

// ── Per-framework scorecards ─────────────────────────────────────────────

func drawFrameworkPage(pdf *reportPDF, fs FrameworkScore) {
	pdf.AddPage()
	pageTitle(pdf, fs.Framework)

	// Score bar + pass/fail counts, side by side.
	x, y := pdf.GetX(), pdf.GetY()
	c := scoreColor(fs.Score)
	setFill(pdf, c)
	pdf.RoundedRect(x, y, 40, 22, 2, "1234", "F")
	setText(pdf, [3]int{255, 255, 255})
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetXY(x, y+3)
	pdf.CellFormat(40, 9, fmt.Sprintf("%d%%", fs.Score), "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(x, y+13)
	pdf.CellFormat(40, 5, pdf.tr(scoreLabel(fs.Score)), "", 1, "C", false, 0, "")

	statX := x + 48
	setText(pdf, colorSuccess)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetXY(statX, y+2)
	pdf.CellFormat(30, 7, fmt.Sprintf("%d", fs.Passed), "", 1, "L", false, 0, "")
	setText(pdf, colorMuted)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(statX, y+9)
	pdf.CellFormat(30, 4, "Passed", "", 1, "L", false, 0, "")

	statX2 := statX + 35
	setText(pdf, colorDanger)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetXY(statX2, y+2)
	pdf.CellFormat(30, 7, fmt.Sprintf("%d", fs.Failed), "", 1, "L", false, 0, "")
	setText(pdf, colorMuted)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(statX2, y+9)
	pdf.CellFormat(30, 4, "Failed", "", 1, "L", false, 0, "")

	pdf.SetXY(x, y+26)
	setText(pdf, [3]int{0, 0, 0})
	pdf.Ln(4)

	sectionHeader(pdf, "Controls")
	tableHeaderRow(pdf, []colSpec{{"", 6}, {"Control", 75}, {"Category", 30}, {"Severity", 22}, {"Detail", 0}})
	for i, check := range fs.Checks {
		drawCheckRow(pdf, check, i%2 == 1)
	}
}

func drawCheckRow(pdf *reportPDF, check ComplianceCheck, zebra bool) {
	rowH := 6.5
	x, y := pdf.GetX(), pdf.GetY()
	if zebra {
		setFill(pdf, colorRowFill)
		pdf.Rect(x, y, pageWidthA4-30, rowH, "F")
	}

	// Pass/fail dot.
	dotColor := colorSuccess
	if !check.Passed {
		dotColor = colorDanger
	}
	setFill(pdf, dotColor)
	pdf.Circle(x+3, y+rowH/2, 1.6, "F")
	pdf.SetXY(x+6, y)

	setText(pdf, [3]int{0, 0, 0})
	pdf.SetFont("Helvetica", "", 8.5)
	cellText(pdf, check.Name, 75, false)

	drawChip(pdf, check.Category, colorChipFill, colorNavy, 30)

	sevC := severityColor(check.Severity)
	drawChip(pdf, check.Severity, sevC, [3]int{255, 255, 255}, 22)

	pdf.SetFont("Helvetica", "", 8)
	setText(pdf, colorMuted)
	pdf.CellFormat(0, rowH, pdf.tr(truncate(check.Detail, 70)), "", 1, "L", false, 0, "")
	setText(pdf, [3]int{0, 0, 0})
}

// drawChip renders a small rounded-rect "badge" with centered text, used for
// category/severity tags inside table rows.
func drawChip(pdf *reportPDF, label string, fill, text [3]int, w float64) {
	x, y := pdf.GetX(), pdf.GetY()
	h := 5.0
	chipW := w - 2
	setFill(pdf, fill)
	pdf.RoundedRect(x, y+0.7, chipW, h, 1.2, "1234", "F")
	setText(pdf, text)
	pdf.SetFont("Helvetica", "", 7.5)
	pdf.CellFormat(chipW, h+0.7, pdf.tr(label), "", 0, "C", false, 0, "")
	pdf.SetXY(x+w, y)
}

// ── Shared layout helpers ────────────────────────────────────────────────

type colSpec struct {
	Label string
	Width float64 // 0 means "fill remaining width"
}

func tableHeaderRow(pdf *reportPDF, cols []colSpec) {
	setFill(pdf, colorNavy)
	setText(pdf, [3]int{255, 255, 255})
	pdf.SetFont("Helvetica", "B", 8.5)
	for _, c := range cols {
		w := c.Width
		ln := 0
		if w == 0 {
			ln = 1
		}
		pdf.CellFormat(w, 6.5, pdf.tr(c.Label), "", ln, "L", true, 0, "")
	}
	setText(pdf, [3]int{0, 0, 0})
}

func startRow(pdf *reportPDF, zebra bool) {
	if zebra {
		x, y := pdf.GetX(), pdf.GetY()
		setFill(pdf, colorRowFill)
		pdf.Rect(x, y, pageWidthA4-30, 6.5, "F")
	}
}

func cellText(pdf *reportPDF, txt string, w float64, lastInRow bool) {
	pdf.SetFont("Helvetica", "", 9)
	ln := 0
	if lastInRow {
		ln = 1
	}
	pdf.CellFormat(w, 6.5, pdf.tr(txt), "", ln, "L", false, 0, "")
}

func pageTitle(pdf *reportPDF, title string) {
	setFill(pdf, colorNavy)
	pdf.Rect(0, 0, pageWidthA4, 22, "F")
	setText(pdf, [3]int{255, 255, 255})
	pdf.SetFont("Helvetica", "B", 15)
	pdf.SetXY(15, 7)
	pdf.CellFormat(0, 9, pdf.tr(title), "", 1, "L", false, 0, "")
	setText(pdf, [3]int{0, 0, 0})
	pdf.SetXY(15, 30)
}

func sectionHeader(pdf *reportPDF, title string) {
	setText(pdf, colorNavy)
	pdf.SetFont("Helvetica", "B", 12)
	setFill(pdf, colorChipFill)
	pdf.CellFormat(0, 8, "  "+title, "", 1, "L", true, 0, "")
	setText(pdf, [3]int{0, 0, 0})
	pdf.SetFont("Helvetica", "", 10)
	pdf.Ln(1)
}

// drawFooter is registered via SetFooterFunc and runs on every page: a thin
// rule, the confidentiality line, and "Page X of {nb}" (the {nb} alias is
// substituted by AliasNbPages once the document is finalized).
func drawFooter(pdf *reportPDF, report *models.ComplianceReport) {
	pdf.SetY(-15)
	setDraw(pdf, colorBorder)
	pdf.SetLineWidth(0.2)
	pdf.Line(15, pdf.GetY(), pageWidthA4-15, pdf.GetY())
	pdf.Ln(2)
	setText(pdf, colorMuted)
	pdf.SetFont("Helvetica", "", 8)
	pdf.CellFormat(95, 5, pdf.tr("XCloak Security Suite — Confidential"), "", 0, "L", false, 0, "")
	pdf.CellFormat(80, 5, fmt.Sprintf("Report #%d", report.ID), "", 0, "C", false, 0, "")
	pdf.CellFormat(0, 5, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "R", false, 0, "")
	setText(pdf, [3]int{0, 0, 0})
}
