package services

// DNS Security Engine
//
// Two detection surfaces:
//
//  1. Connection-level (always active): analyses DNS query volume from
//     endpoint_connections and network_connect_events to detect DNS floods
//     and suspicious query bursts. No domain name needed — port 53 traffic
//     alone is sufficient to flag volumetric attacks or C2-via-DNS patterns.
//
//  2. Log-level (activates automatically when DNS logs arrive via syslog or
//     HTTP ingest): inspects actual domain names for DGA patterns, excessively
//     long subdomains (tunneling), and direct IOC matches. Works with any DNS
//     server that forwards logs: BIND, Unbound, Pi-hole, Windows DNS, Palo Alto.

import (
	"fmt"
	"log"
	"math"
	"net"
	"regexp"
	"strings"
	"time"

	"xcloak-platform/database"
	"xcloak-platform/models"
)

// StartDNSSecurityScheduler runs DNS volume analysis every 30 minutes.
func StartDNSSecurityScheduler() {
	go func() {
		time.Sleep(5 * time.Minute)
		runDNSAnalysisAll()
		for {
			time.Sleep(30 * time.Minute)
			runDNSAnalysisAll()
		}
	}()
}

func runDNSAnalysisAll() {
	rows, err := database.DB.Query(`SELECT id FROM tenants WHERE is_active = true`)
	if err != nil {
		return
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		if rows.Scan(&id) == nil {
			AnalyzeDNSForTenant(id)
		}
	}
}

// ── Volume-level detection ────────────────────────────────────────────────────

// AnalyzeDNSForTenant scans the last hour of connection events for anomalous
// DNS query volume per agent.
func AnalyzeDNSForTenant(tenantID int) {
	// Count DNS connections (dst port 53) per agent in the last hour.
	// Baseline: look at the 7-day average (excluding the last hour).
	rows, err := database.DB.Query(`
		WITH hour_count AS (
			SELECT agent_id, COUNT(*) AS n
			FROM network_connect_events
			WHERE tenant_id = $1
			  AND created_at > NOW() - INTERVAL '1 hour'
			  AND remote_address LIKE '%:53'
			GROUP BY agent_id
		),
		baseline AS (
			SELECT agent_id,
			       COUNT(*)::float / GREATEST(
			           EXTRACT(EPOCH FROM (NOW() - INTERVAL '1 hour' - (NOW() - INTERVAL '7 days')))/3600,
			           1
			       ) AS avg_per_hour
			FROM network_connect_events
			WHERE tenant_id = $1
			  AND created_at BETWEEN NOW()-INTERVAL '7 days' AND NOW()-INTERVAL '1 hour'
			  AND remote_address LIKE '%:53'
			GROUP BY agent_id
		)
		SELECT h.agent_id, h.n,
		       COALESCE(b.avg_per_hour, 0) AS avg_per_hour
		FROM hour_count h
		LEFT JOIN baseline b USING (agent_id)
		WHERE h.n > 50
	`, tenantID)
	if err != nil {
		return
	}
	defer rows.Close()

	for rows.Next() {
		var agentID int
		var count int
		var avgPerHour float64
		if err := rows.Scan(&agentID, &count, &avgPerHour); err != nil {
			continue
		}

		// Skip if within 3x the normal baseline
		if avgPerHour > 0 && float64(count) < avgPerHour*3 {
			continue
		}

		// Absolute threshold: >500 DNS queries/hour is suspicious even without baseline
		if count < 200 {
			continue
		}

		score := 60
		desc := fmt.Sprintf("DNS flood: %d queries/hour (baseline ~%.0f/hour)", count, avgPerHour)

		// Very high volume → higher severity
		if count > 1000 {
			score = 85
			desc = fmt.Sprintf("Severe DNS flood: %d queries/hour — possible DNS tunneling or C2 via DNS", count)
		}

		// Dedup
		var existing int
		database.DB.QueryRow(`
			SELECT COUNT(*) FROM network_anomalies
			WHERE agent_id=$1 AND anomaly_type='dns_flood'
			  AND detected_at > NOW()-INTERVAL '2 hours'
		`, agentID).Scan(&existing)
		if existing > 0 {
			continue
		}

		database.DB.Exec(`
			INSERT INTO network_anomalies
			  (agent_id, tenant_id, anomaly_type, dst_ip, dst_port, proto,
			   deviation_score, description)
			VALUES ($1,$2,'dns_flood','0.0.0.0',53,'udp',$3,$4)
		`, agentID, tenantID, score, desc)

		log.Printf("[DNS] tenant=%d agent=%d dns_flood count=%d", tenantID, agentID, count)

		if score >= 75 {
			alert := models.Alert{
				AgentID:        agentID,
				TenantID:       tenantID,
				RuleName:       "DNS Flood Detected",
				Severity:       "high",
				LogMessage:     desc,
				MitreTechnique: "T1071.004", // DNS Application Layer Protocol
				Fingerprint:    fmt.Sprintf("%d-dnsfloood-%d", agentID, time.Now().Unix()/3600),
			}
			CreateAlert(alert) //nolint:errcheck
		}
	}
}

// ── Log-level detection (domain analysis) ────────────────────────────────────

// AnalyzeDNSLogEntry is called for every log line that passes through the
// ingest pipeline and appears to contain a DNS query record. The caller
// (DetectThreats) invokes this after normalizing the log when the parsed
// fields hint at DNS activity.
//
// Detection coverage:
//   - DGA domain (high character-level entropy → likely generated by malware)
//   - DNS tunneling (subdomain length > threshold, or query rate anomaly)
//   - Direct IOC match (domain is in the tenant's IOC database)
//   - NXDOMAIN storm (rapid failed lookups — DGA rotation or C2 probing)
func AnalyzeDNSLogEntry(agentID, tenantID int, domain string) {
	if domain == "" || isPublicDNSServer(domain) {
		return
	}

	domain = strings.ToLower(strings.TrimSuffix(domain, "."))
	parts := strings.Split(domain, ".")
	if len(parts) < 2 {
		return
	}

	var findings []string

	// 1. DGA detection via multi-factor scorer (delegates to dga_detector.go)
	dgaS := ScoreDomainDGA(agentID, tenantID, domain)
	if dgaS >= 50 {
		findings = append(findings, fmt.Sprintf("dga_score(%d)", dgaS))
	}

	// 2. Subdomain tunneling: excessively long subdomain chain
	totalSubLen := len(strings.Join(parts[:len(parts)-2], "."))
	if len(parts) > 4 && totalSubLen > 50 {
		findings = append(findings, "long_subdomain_chain")
	}

	// 3. IOC database match
	var iocCount int
	database.DB.QueryRow(`
		SELECT COUNT(*) FROM iocs
		WHERE tenant_id=$1 AND indicator=$2 AND ioc_type IN ('domain','fqdn','c2')
	`, tenantID, domain).Scan(&iocCount)
	// Also check base domain (e.g. "evil.com" in IOC list should match "sub.evil.com")
	if iocCount == 0 && len(parts) >= 2 {
		baseDomain := strings.Join(parts[len(parts)-2:], ".")
		database.DB.QueryRow(`
			SELECT COUNT(*) FROM iocs
			WHERE tenant_id=$1 AND indicator=$2 AND ioc_type IN ('domain','fqdn','c2')
		`, tenantID, baseDomain).Scan(&iocCount)
	}
	if iocCount > 0 {
		findings = append(findings, "ioc_match")
	}

	if len(findings) == 0 {
		return
	}

	score := 0
	for _, f := range findings {
		switch {
		case strings.HasPrefix(f, "dga_score("):
			// parse score from "dga_score(75)" for proportional contribution
			var dS int
			fmt.Sscanf(f, "dga_score(%d)", &dS)
			score += dS / 2
		case f == "long_subdomain_chain":
			score += 40
		case f == "ioc_match":
			score += 70
		}
	}
	if score > 100 {
		score = 100
	}
	if score < 50 {
		return
	}

	desc := fmt.Sprintf("Suspicious DNS query for %q. Indicators: %s", domain, strings.Join(findings, ", "))

	var existing int
	database.DB.QueryRow(`
		SELECT COUNT(*) FROM network_anomalies
		WHERE agent_id=$1 AND anomaly_type='dns_suspicious'
		  AND description LIKE $2 AND detected_at > NOW()-INTERVAL '1 hour'
	`, agentID, "%"+domain+"%").Scan(&existing)
	if existing > 0 {
		return
	}

	database.DB.Exec(`
		INSERT INTO network_anomalies
		  (agent_id, tenant_id, anomaly_type, dst_ip, dst_port, proto,
		   deviation_score, description)
		VALUES ($1,$2,'dns_suspicious',$3,53,'udp',$4,$5)
	`, agentID, tenantID, domain, score, desc)

	if score >= 70 {
		severity := "medium"
		ruleName := "Suspicious DNS Activity"
		mitre := "T1071.004"
		if iocCount > 0 {
			severity = "high"
			ruleName = "Malicious Domain Contacted"
			mitre = "T1071.004"
		}

		alert := models.Alert{
			AgentID:        agentID,
			TenantID:       tenantID,
			RuleName:       ruleName,
			Severity:       severity,
			LogMessage:     desc,
			MitreTechnique: mitre,
			Fingerprint:    fmt.Sprintf("%d-dns-%s", agentID, domain),
		}
		CreateAlert(alert) //nolint:errcheck
	}
}

// ── DNS log field extraction ──────────────────────────────────────────────────

// dnsQueryRE matches common DNS log formats (BIND, Unbound, dnsmasq).
var dnsQueryRE = regexp.MustCompile(
	`(?i)query(?:\[A\])?[:\s]+([a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,})`,
)

// ExtractDNSDomain attempts to parse a domain name from a raw log line.
// Returns empty string if the log doesn't look like a DNS query log.
func ExtractDNSDomain(logMessage string) string {
	m := dnsQueryRE.FindStringSubmatch(logMessage)
	if len(m) >= 2 {
		return m[1]
	}
	// Fallback: look for " IN A " / " IN AAAA " patterns (BIND format)
	if strings.Contains(logMessage, " IN A ") || strings.Contains(logMessage, " IN AAAA ") {
		fields := strings.Fields(logMessage)
		for i, f := range fields {
			if (f == "A" || f == "AAAA") && i > 0 {
				return strings.TrimSuffix(fields[i-1], ".")
			}
		}
	}
	return ""
}

// IsDNSLog returns true if the log line looks like a DNS server query log.
func IsDNSLog(logSource, logMessage string) bool {
	src := strings.ToLower(logSource)
	if strings.Contains(src, "dns") || strings.Contains(src, "bind") ||
		strings.Contains(src, "unbound") || strings.Contains(src, "dnsmasq") {
		return true
	}
	msg := strings.ToLower(logMessage)
	return strings.Contains(msg, "query[") || strings.Contains(msg, "dns query") ||
		strings.Contains(msg, " in a ") || strings.Contains(msg, " in aaaa ")
}

// ── Helpers ──────────────────────────────────────────────────────────────────

func shannonEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}
	freq := make(map[rune]float64)
	for _, c := range s {
		freq[c]++
	}
	n := float64(len(s))
	var entropy float64
	for _, count := range freq {
		p := count / n
		entropy -= p * math.Log2(p)
	}
	return entropy
}

func isPublicDNSServer(domain string) bool {
	// Skip reverse-DNS lookups (in-addr.arpa)
	return strings.HasSuffix(domain, ".arpa")
}

// isPrivateDNSIP returns true if the target is a typical internal DNS server.
// Used to skip counting queries to the local resolver as "DNS flood".
func isPrivateDNSIP(ip string) bool {
	parsed := net.ParseIP(ip)
	if parsed == nil {
		return false
	}
	// Common internal DNS servers
	for _, cidr := range []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"} {
		_, network, _ := net.ParseCIDR(cidr)
		if network != nil && network.Contains(parsed) {
			return true
		}
	}
	return false
}
