package services

// Mobile MDM — enrollment token management and self-enroll flow.
//
// Desktop agents register via POST /api/agents/register with a machine_id and
// receive a random hex token. Mobile devices can't authenticate as a logged-in
// user, so they present a pre-shared enrollment token (generated by an admin)
// to POST /api/mdm/self-enroll and receive an agent token in return.
//
// After self-enroll the mobile agent uses that agent_token for all subsequent
// calls: heartbeat, log ingest, command polling, and command acknowledge.

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"xcloak-platform/database"
)

// ── Enrollment token management ───────────────────────────────────────────────

type EnrollmentToken struct {
	ID        int        `json:"id"`
	TenantID  int        `json:"tenant_id"`
	Token     string     `json:"token"`
	Label     string     `json:"label"`
	Platform  string     `json:"platform"`
	UsedCount int        `json:"used_count"`
	MaxUses   *int       `json:"max_uses"`
	ExpiresAt *time.Time `json:"expires_at"`
	CreatedBy *int       `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
}

func CreateEnrollmentToken(tenantID int, label, platform string, maxUses *int, expiresAt *time.Time, createdBy int) (EnrollmentToken, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return EnrollmentToken{}, err
	}
	token := "xck-enroll-" + hex.EncodeToString(raw)
	if platform == "" {
		platform = "android"
	}
	var t EnrollmentToken
	err := database.DB.QueryRow(`
		INSERT INTO mdm_enrollment_tokens
			(tenant_id, token, label, platform, max_uses, expires_at, created_by)
		VALUES ($1,$2,$3,$4,$5,$6,$7)
		RETURNING id, tenant_id, token, label, platform, used_count, max_uses, expires_at, created_by, created_at
	`, tenantID, token, label, platform, maxUses, expiresAt, createdBy).Scan(
		&t.ID, &t.TenantID, &t.Token, &t.Label, &t.Platform,
		&t.UsedCount, &t.MaxUses, &t.ExpiresAt, &t.CreatedBy, &t.CreatedAt,
	)
	return t, err
}

func ListEnrollmentTokens(tenantID int) ([]EnrollmentToken, error) {
	rows, err := database.DB.Query(`
		SELECT id, tenant_id, token, label, platform, used_count, max_uses, expires_at, created_by, created_at
		FROM mdm_enrollment_tokens
		WHERE tenant_id=$1
		ORDER BY created_at DESC
	`, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []EnrollmentToken{}
	for rows.Next() {
		var t EnrollmentToken
		if err := rows.Scan(&t.ID, &t.TenantID, &t.Token, &t.Label, &t.Platform,
			&t.UsedCount, &t.MaxUses, &t.ExpiresAt, &t.CreatedBy, &t.CreatedAt); err == nil {
			out = append(out, t)
		}
	}
	if out == nil {
		out = []EnrollmentToken{}
	}
	return out, nil
}

func RevokeEnrollmentToken(id, tenantID int) error {
	res, err := database.DB.Exec(
		`DELETE FROM mdm_enrollment_tokens WHERE id=$1 AND tenant_id=$2`, id, tenantID,
	)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return errors.New("token not found")
	}
	return nil
}

// ── Self-enrollment ───────────────────────────────────────────────────────────

type SelfEnrollResult struct {
	DeviceID   int    `json:"device_id"`
	AgentToken string `json:"agent_token"`
	AgentID    int    `json:"agent_id"`
}

// SelfEnrollDevice validates an enrollment token, upserts the MDMDevice record,
// and ensures a linked Agent record exists so the device can use RequireAgentAuth.
func SelfEnrollDevice(enrollToken string, d MDMDevice) (SelfEnrollResult, error) {
	// ── 1. Validate enrollment token ─────────────────────────────────────────
	var tokenID, tenantID int
	var maxUses *int
	var expiresAt *time.Time
	var platform string
	err := database.DB.QueryRow(`
		SELECT id, tenant_id, max_uses, expires_at, platform
		FROM mdm_enrollment_tokens
		WHERE token=$1
	`, enrollToken).Scan(&tokenID, &tenantID, &maxUses, &expiresAt, &platform)
	if err != nil {
		return SelfEnrollResult{}, errors.New("invalid enrollment token")
	}
	if expiresAt != nil && time.Now().After(*expiresAt) {
		return SelfEnrollResult{}, errors.New("enrollment token has expired")
	}
	if maxUses != nil {
		var used int
		database.DB.QueryRow(
			`SELECT used_count FROM mdm_enrollment_tokens WHERE id=$1`, tokenID,
		).Scan(&used)
		if used >= *maxUses {
			return SelfEnrollResult{}, errors.New("enrollment token has reached its maximum use count")
		}
	}

	d.TenantID = tenantID
	if d.Platform == "" {
		d.Platform = platform
	}

	// ── 2. Upsert MDMDevice ───────────────────────────────────────────────────
	deviceID, err := EnrollDevice(d)
	if err != nil {
		return SelfEnrollResult{}, fmt.Errorf("device enrollment: %w", err)
	}

	// ── 3. Ensure Agent record exists so RequireAgentAuth works ───────────────
	agentID, agentToken, err := ensureMobileAgent(tenantID, deviceID, d)
	if err != nil {
		return SelfEnrollResult{}, fmt.Errorf("agent record: %w", err)
	}
	database.DB.Exec(`UPDATE mdm_devices SET agent_id=$1 WHERE id=$2`, agentID, deviceID)

	// ── 4. Increment usage counter ────────────────────────────────────────────
	database.DB.Exec(
		`UPDATE mdm_enrollment_tokens SET used_count=used_count+1 WHERE id=$1`, tokenID,
	)

	LogEvent("MDM_SELF_ENROLL",
		fmt.Sprintf("device_id=%d udid=%s platform=%s", deviceID, d.UDID, d.Platform),
		"agent")

	return SelfEnrollResult{DeviceID: deviceID, AgentToken: agentToken, AgentID: agentID}, nil
}

// ensureMobileAgent creates or returns the Agent row linked to an MDMDevice.
// We use the device's UDID as the machine_id so the same agent token is
// returned on re-enrollment.
func ensureMobileAgent(tenantID, deviceID int, d MDMDevice) (int, string, error) {
	// Check if this UDID already has an agent row.
	var existingID int
	var existingToken string
	_ = database.DB.QueryRow(
		`SELECT id, token FROM agents WHERE machine_id=$1`, d.UDID,
	).Scan(&existingID, &existingToken)
	if existingID > 0 && existingToken != "" {
		return existingID, existingToken, nil
	}

	hostname := d.DeviceName
	if hostname == "" {
		hostname = d.UDID
	}
	newToken, err := generateToken()
	if err != nil {
		return 0, "", err
	}

	var agentID int
	err = database.DB.QueryRow(`
		INSERT INTO agents
			(machine_id, hostname, os, ip_address, status, token, last_seen, tenant_id)
		VALUES ($1, $2, $3, '', 'online', $4, NOW(), $5)
		ON CONFLICT (machine_id) DO UPDATE SET
			hostname  = EXCLUDED.hostname,
			os        = EXCLUDED.os,
			status    = 'online',
			last_seen = NOW()
		RETURNING id, token
	`, d.UDID, hostname, d.Platform, newToken, tenantID).Scan(&agentID, &newToken)
	if err != nil {
		return 0, "", err
	}

	UpdateAgentPlatform(agentID, d.Platform)
	return agentID, newToken, nil
}

// ── Agent-authenticated device operations ────────────────────────────────────

// DeviceCheckIn updates posture fields and records a heartbeat from the device.
// Called by the mobile agent every few minutes with fresh device state.
func DeviceCheckIn(deviceID, tenantID int, d MDMDevice) error {
	_, err := database.DB.Exec(`
		UPDATE mdm_devices SET
			os_version         = COALESCE(NULLIF($3,''),  os_version),
			build_version      = COALESCE(NULLIF($4,''),  build_version),
			is_encrypted       = COALESCE($5,             is_encrypted),
			has_passcode       = COALESCE($6,             has_passcode),
			passcode_compliant = COALESCE($7,             passcode_compliant),
			is_jailbroken      = $8,
			developer_mode_on  = $9,
			push_token         = COALESCE(NULLIF($10,''), push_token),
			last_check_in      = NOW(),
			status             = 'enrolled'
		WHERE id=$1 AND tenant_id=$2
	`, deviceID, tenantID,
		d.OSVersion, d.BuildVersion,
		d.IsEncrypted, d.HasPasscode, d.PasscodeCompliant,
		d.IsJailbroken, d.DeveloperModeOn, d.PushToken,
	)
	return err
}

// GetPendingMobileCommands returns queued commands for the device.
// The mobile agent polls this because FCM push is optional.
func GetPendingMobileCommands(deviceID, tenantID int) ([]MDMCommand, error) {
	rows, err := database.DB.Query(`
		SELECT id, tenant_id, device_id, command_type, payload, status,
		       queued_by, queued_at, sent_at, acknowledged_at, COALESCE(error_msg,'')
		FROM mdm_commands
		WHERE device_id=$1 AND tenant_id=$2 AND status='pending'
		ORDER BY queued_at ASC
		LIMIT 10
	`, deviceID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cmds := []MDMCommand{}
	for rows.Next() {
		var c MDMCommand
		payloadJSON := []byte{}
		if err := rows.Scan(&c.ID, &c.TenantID, &c.DeviceID, &c.CommandType,
			&payloadJSON, &c.Status, &c.QueuedBy, &c.QueuedAt,
			&c.SentAt, &c.AcknowledgedAt, &c.ErrorMsg); err != nil {
			continue
		}
		json.Unmarshal(payloadJSON, &c.Payload)
		database.DB.Exec(
			`UPDATE mdm_commands SET status='sent', sent_at=NOW() WHERE id=$1`, c.ID,
		)
		cmds = append(cmds, c)
	}
	if cmds == nil {
		cmds = []MDMCommand{}
	}
	return cmds, nil
}

// LookupDeviceByAgent returns the MDMDevice ID linked to an agent.
func LookupDeviceByAgent(agentID, tenantID int) (int, error) {
	var deviceID int
	err := database.DB.QueryRow(
		`SELECT id FROM mdm_devices WHERE agent_id=$1 AND tenant_id=$2 AND status!='unenrolled'`,
		agentID, tenantID,
	).Scan(&deviceID)
	if err != nil {
		return 0, errors.New("no enrolled device found for this agent")
	}
	return deviceID, nil
}

// ── App inventory ─────────────────────────────────────────────────────────────

type AppInfo struct {
	PackageName string `json:"package_name"`
	AppName     string `json:"app_name"`
	Version     string `json:"version"`
	Installer   string `json:"installer"` // "com.android.vending" = Play; "" = sideloaded
}

// SubmitAppInventory replaces the stored app list for threat analysis.
func SubmitAppInventory(deviceID, tenantID int, apps []AppInfo) error {
	if len(apps) == 0 {
		return nil
	}
	tx, err := database.DB.Begin()
	if err != nil {
		return err
	}
	if _, err := tx.Exec(`DELETE FROM mdm_device_apps WHERE device_id=$1`, deviceID); err != nil {
		tx.Rollback()
		return err
	}
	for _, app := range apps {
		if _, err := tx.Exec(`
			INSERT INTO mdm_device_apps
				(device_id, tenant_id, package_name, app_name, version, installer)
			VALUES ($1,$2,$3,$4,$5,$6)
		`, deviceID, tenantID, app.PackageName, app.AppName, app.Version, app.Installer); err != nil {
			tx.Rollback()
			return err
		}
	}
	return tx.Commit()
}
